# Generated by Django 5.1.6 on 2025-02-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compra',
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalle_compra',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='localidad',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategoria',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tipo_usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
