# Generated by Django 5.1.6 on 2025-02-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_alter_categoria_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'forma_pago',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.formapago'),
        ),
    ]
