# Generated by Django 5.1.6 on 2025-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0004_remove_usuario_tipo_usuario_alter_empleado_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
