# Generated by Django 5.1.6 on 2025-02-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0005_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.proveedor'),
        ),
        migrations.CreateModel(
            name='VentaFormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.formapago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.venta')),
            ],
            options={
                'db_table': 'venta_forma_pago',
            },
        ),
    ]
